# classe Livro
# função menu
# função de cadastro
# função de listagem
# função de venda
#   funcao de resumo (venda e estoque)

# PASSO 1
# MODELAGEM DE DADOS
# ENTRADA DE DADOS
# SAÍDA DE DADOS
# ENTENDER O PROBLEMA REAL

# PASSO 2
# DEFINIÇÃO DE FERRAMENTAS
# DEFINIÇÃO E INSTANCIAMENTO DE FUNÇÕES
# PLANEJAMENTO DA LÓGICA

# PASSO 3
# PROGRAMAR
# ARQUITETURA DE DADOS
# FLUXOGRAMA DE FUNCIONALIDADE

# PASSO 4
# TIPOS DE ERROS E BUGS QUE PODEM DAR NOS PASSOS