# classe Livro
# função/método de cadastro
# função/método de listagem
# função/método de venda
# função/método de resumo (venda e estoque)

# O QUE ENTREGAR


# PASSO 1
# MODELAGEM DE DADOS
# ENTRADA DE DADOS
# SAÍDA DE DADOS
# ENTENDER O PROBLEMA REAL

# PASSO 2
# DEFINIÇÃO DE FERRAMENTAS
# DEFINIÇÃO E INSTANCIAMENTO DE FUNÇÕES
# PLANEJAMENTO DA LÓGICA

# PASSO 3
# PROGRAMAR
# ARQUITETURA DE DADOS
# FLUXOGRAMA DE FUNCIONALIDADE

# PASSO 4
# TIPOS DE ERROS E BUGS QUE PODEM DAR NOS PASSOS


# ETAPA 1
# MODELAGEM DE DADOS/DEFINIR FERRAMENTAS

# ETAPA 2
# SINTAXE

# ETAPA 3
# INTEGRAÇÃO DE SISTEMA

# ETAPA 4
# CONTAINER - PREVENSÃO DE BUGS

# ETAPA 5
# DEPLOY/VERSIONAMENTO



# ATRIBUTOS
# LIVRO (DICIONARIO)
    # ID
    # TITULO
    # AUTOR
    # PRECO
    # ESTOQUE
    # EDITORA
    # GENERO
    # DATA DE CADASTRO
    # DATA DE ALTERACAO

# VENDA
    # ID
    # DATA VENDA
    # VALOR BRUTO
    # DESCONTO APLICADO
    # VALOR LIQUIDO

# ITEM VENDA
    # % DESCONTO
    # LIMITE DESCONTO
    # IMPOSTO
    # VALOR DO LIVRO
    # ID CLIENTE
    # ID VENDA